---
- hosts: mywebservers
  become: yes
  tasks: 
   - name: i want to install webserver on ubuntu nodes
     apt:
       name: "{{mywebpackageforubuntu}}"
       state: present
     when: ansible_os_family =="Debian"

   - name: i want to start webserver on ubuntu nodes
     service:
        name: "{{mywebpackageforubuntu}}"
        state: started
     when: ansible_os_family =="Debian"

   - name: i want to install webserver on amazon nodes
     yum:
       name: "{{mywebpackageforRedhat}}"
       state: present
     when: ansible_os_family =="RedHat"

   - name: i want to start webserver on amazon nodes
     service:
        name: "{{mywebpackageforRedhat}}"
        state: started
     when: ansible_os_family =="RedHat"
                      
